/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "app.getGameData", input: never, result: [string, string][] } | 
        { key: "app.playSpeedUpdate", input: number, result: null } | 
        { key: "app.refresh", input: never, result: null } | 
        { key: "app.selectGameId", input: string | null, result: null },
    mutations: never,
    subscriptions: never
};
