/*
 Generated by typeshare 1.3.0
*/

export interface PlaySpeedUpdate {
	speed: number;
}

export interface Citizen {
	id: number;
	name: string;
	born_timestamp: number;
	death_timestamp?: number;
	gender: Gender;
	job?: string;
	staying_city_id: number;
	home_city_id: number;
	country_id?: number;
	relations: Record<number, Relation>;
}

export interface Relation {
	id: number;
	name: string;
	impression: number;
	relation_type: RelationType;
	last_met_timestamp: number;
}

export interface City {
	id: number;
	name: string;
	position_x: number;
	position_y: number;
	dev_production: number;
	dev_building: number;
	dev_infrastructure: number;
	exp_dev_production: number;
	exp_dev_building: number;
	exp_dev_infrastructure: number;
	control: number;
	environment: number;
	region_id: number;
	country_id?: number;
}

export interface Region {
	id: number;
	name: string;
	product: string;
	country_id?: number;
	position_x: number;
	position_y: number;
}

export enum RelationType {
	Child = "Child",
	Parent = "Parent",
	Sibling = "Sibling",
	Partner = "Partner",
	Acquaintance = "Acquaintance",
	Clan = "Clan",
}

export enum Gender {
	Male = "Male",
	Female = "Female",
}

